CC = gcc
ZIEL = primzahlzwilling
OBJECT = primzahlzwilling.o
CLEAN = rm -f

$(ZIEL): $(OBJECT)
	$(CC) -o $(ZIEL) primzahlzwilling.c -lm

clean:
	$(CLEAN) $(OBJECT)

cleanall:
	$(CLEAN) $(OBJECT) $(ZIEL)
